---
development:
  cloud_name: hrufx4cv2
  api_key: '812181537692788'
  api_secret: NSEmhyS_IZnIRi2CwsXdcCv92ps
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hrufx4cv2
  api_key: '812181537692788'
  api_secret: NSEmhyS_IZnIRi2CwsXdcCv92ps
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hrufx4cv2
  api_key: '812181537692788'
  api_secret: NSEmhyS_IZnIRi2CwsXdcCv92ps
  enhance_image_tag: true
  static_image_support: false
